export {
  abortBeforeReveal,
  BATTLE_STATUSES,
  BATTLE_TRANSITIONS,
  cancelPending,
  canTransition,
  COUNTDOWN_SECONDS,
  DEFAULT_TIME_LIMIT_SECONDS,
  DISCONNECT_GRACE_SECONDS,
  flagBattle,
  forfeitBattle,
  liveDeadline,
  markReady,
  matchBattle,
  opponentOf,
  READY_WINDOW_SECONDS,
  resolveDecisive,
  tickBattle,
  type AbortResult,
  type BattleEffect,
  type BattleSnapshot,
  type BattleStatus,
  type CancelResult,
  type FlagResult,
  type ForfeitReason,
  type ForfeitResult,
  type MatchResult,
  type PlayerSide,
  type ReadyResult,
  type ResolveResult,
  type TickResult,
} from './lifecycle';
export {
  DEFAULT_PENALTY_PER_WRONG_SECONDS,
  scoreBattle,
  SUBMISSION_COOLDOWN_SECONDS,
  submissionCooldownRemaining,
  type BattleOutcome,
  type BattleSubmission,
  type PlayerScore,
} from './scoring';
// `wager-settlement` is DELIBERATELY not re-exported: it is Phase 2 domain
// design (tested now, wired to nothing) and nothing outside its own tests may
// reference it until wagering ships behind the wallet/KYC/escrow build.
