export {
  assessAuthorship,
  assessBattleIntegrity,
  assessCadence,
  assessPlagiarism,
  DEFAULT_BATTLE_INTEGRITY_THRESHOLDS,
  focusLossSeconds,
  isTelemetryKind,
  TELEMETRY_KINDS,
  type AuthorshipEvidence,
  type BattleCheatReason,
  type BattleCheatSignal,
  type BattleComparisonKind,
  type BattleIntegrityInput,
  type BattleIntegrityThresholds,
  type BattleIntegrityVerdict,
  type BattleSimilarityComparison,
  type CadenceEvidence,
  type MatchTelemetryRecord,
  type TelemetryKind,
} from './anti-cheat';
export {
  applyCheatSanction,
  BAN_LADDER_DAYS,
  banDaysForStrikes,
  CHEAT_ELO_PENALTY,
  isBattleBanned,
  reviewBattleFlag,
  type BattleReviewDecision,
  type BattleReviewOutcome,
  type CheatSanction,
  type ReviewBattleFlagResult,
} from './sanctions';
export {
  abortBeforeReveal,
  ACTIVE_BATTLE_STATUSES,
  BATTLE_STATUSES,
  BATTLE_TRANSITIONS,
  cancelPending,
  canTransition,
  COUNTDOWN_SECONDS,
  DEFAULT_TIME_LIMIT_SECONDS,
  DISCONNECT_GRACE_SECONDS,
  flagBattle,
  forfeitBattle,
  liveDeadline,
  markReady,
  matchBattle,
  opponentOf,
  READY_WINDOW_SECONDS,
  resolveDecisive,
  tickBattle,
  type AbortResult,
  type BattleEffect,
  type BattleSnapshot,
  type BattleStatus,
  type CancelResult,
  type FlagResult,
  type ForfeitReason,
  type ForfeitResult,
  type MatchResult,
  type PlayerSide,
  type ReadyResult,
  type ResolveResult,
  type TickResult,
} from './lifecycle';
export {
  allowedEloGap,
  pairQueue,
  QUEUE_BASE_ELO_GAP,
  QUEUE_WIDEN_PER_SECOND,
  type QueuePairing,
  type QueueTicket,
} from './matchmaking';
export {
  DEFAULT_PENALTY_PER_WRONG_SECONDS,
  scoreBattle,
  SUBMISSION_COOLDOWN_SECONDS,
  submissionCooldownRemaining,
  type BattleOutcome,
  type BattleSubmission,
  type PlayerScore,
} from './scoring';
export {
  approveProblem,
  BATTLE_LANGUAGES,
  checkProblemSpec,
  isBattleLanguage,
  isPlayable,
  isProblemTier,
  MIN_HIDDEN_TESTS,
  PROBLEM_STATUSES,
  PROBLEM_TIERS,
  retireProblem,
  type ApproveProblemResult,
  type BattleLanguage,
  type HiddenTest,
  type ProblemSpec,
  type ProblemSpecCheck,
  type ProblemSpecRejection,
  type ProblemStatus,
  type ProblemTier,
  type RetireProblemResult,
} from './problems';
// `wager-settlement` is DELIBERATELY not re-exported: it is Phase 2 domain
// design (tested now, wired to nothing) and nothing outside its own tests may
// reference it until wagering ships behind the wallet/KYC/escrow build.
